name: Deploy Lambda Function

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.5.7

jobs:
  terraform-checks:
    name: Terraform Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        id: fmt
        working-directory: ./terraform
        run: |
          if [ -f "backend.tf" ] || [ -f "provider.tf" ] || [ -f "main.tf" ]; then
            terraform fmt -check -recursive || echo "::warning::Some files need formatting. Run 'terraform fmt' to fix."
          else
            echo "No Terraform files found, skipping format check"
          fi

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform Validate
        id: validate
        working-directory: ./terraform
        run: terraform validate -no-color

      - name: Setup Snyk
        if: ${{ github.event_name == 'pull_request' }}
        uses: snyk/actions/setup@master
        continue-on-error: true
        with:
          skip-auth: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Scan
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: ./terraform
        run: |
          if [ -f "main.tf" ]; then
            npx snyk test --severity-threshold=high --file=main.tf || echo "::warning::Snyk found vulnerabilities"
          else
            echo "No main.tf found, skipping Snyk scan"
          fi

  deploy:
    name: Deploy Infrastructure
    needs: [terraform-checks]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false